# Generated by Django 2.1.1 on 2018-11-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='userid',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
