# Generated by Django 2.1.1 on 2018-11-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181118_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='userid',
            field=models.IntegerField(max_length=11, unique=True),
        ),
    ]
