# Generated by Django 2.1.1 on 2018-11-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181118_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='userid',
            field=models.IntegerField(max_length=9, unique=True),
        ),
    ]
