# Generated by Django 2.1.3 on 2018-11-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181118_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_details',
            name='quiz_instance',
        ),
        migrations.AlterField(
            model_name='auth',
            name='userid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='q_details',
            name='subject_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
