# Generated by Django 2.1.3 on 2018-11-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20181123_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(max_length=50),
        ),
    ]
